### ISSUE TITLE
A common solution for plotting our results

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps#285]
These will be uploaded and kept pristine, so we don't need to keep passing around analysis/plotting scripts and duplicating effort.

Perhaps a good place for these is the separate GitHub repository, described in #283.

if these are well written and maintained enough, explaining an analysis method should be as simple as "I ran x config json in the test repo, and my results were plotted using y script from the test repo".

Then we have a single source of truth for our plotting/analysis scripts, which we can all see, and correct if necessary. Besides minimising duplication of effort, this would prevent e.g. the issue we had where the plots were mixing up baseline and intervention.

**Comment by jzhu20** [comment]
@TinyMarsh I've put my R script in this sharefolder. https://imperiallondon-my.sharepoint.com/:f:/g/personal/jjo11_ic_ac_uk/EuIeELrQ5txOubPiGNIJCcMBBaEsNzWYgmUzxn6ki2sFRQ?email=ryan.smith%40imperial.ac.uk&e=8LL3Lg

**Comment by TinyMarsh** [comment]
Thanks @jzhu20. I requested any plotting scripts from @jackolney earlier also. It looks like the scripts will entirely be in R. In which case I propose a repository that uses [renv](https://rstudio.github.io/renv/articles/renv.html). This seems like a sensible way to pin packages.

**Comment by jamesturner246** [comment]
See #290: results must be weighted by count column.

**Comment by jamesturner246** [comment]
Thanks again @TinyMarsh -- nice to know we have a single bug-free plot script now.

A couple of points:

1. When I run `Vidualisation.R`, I get the following:
```
Attaching package: ‘collapse’

The following object is masked from ‘package:stats’:

    D
****
Is that normal/okay?

2. Right now the script expects four files. Would be fine to relax this to just processing a single file at a time -- i.e. remove all the lines not relating to policy/data S1. 

Cheers,

**Comment by TinyMarsh** [comment]
1. Yes it's normal. It's explained a bit here: https://stats.oarc.ucla.edu/r/faq/how-does-r-handle-overlapping-object-names/ . Essentially, two packages are being loaded with the same function name 'D', and the warning is letting you know that the 'D' function in the 'collapse' package is what R will use whenever 'D' is called. This is determined by the order in which packages are loaded. Since 'D' is never called explicitly in the script, it's not clear to me if this is what we intend. It's also not clear to me if 'D' is actually ever called (it might be being called behind the scenes from another function), there's probably a way to check that though, and we probably should.
2. I can make that change, but do we want to do away with the functionality of being able to process four files altogether? Perhaps I could make it so than an arbitrary number of files are able to be process (with a lower limit of 1, of course)?

**Comment by TinyMarsh** [comment]
Oh, never mind. I just realised that question is already being answered by https://github.com/imperialCHEPI/healthgps-plots/issues/1.

**Comment by jamesturner246** [comment]
Yeah, sorry, I should have updated this one.

**Comment by TinyMarsh** [comment]
@jackolney are you happy with the new repository and for this issue to be closed?

**Comment by jamesturner246** [comment]
Since work here is continuing in https://github.com/imperialCHEPI/healthgps-plots/pull/3 and we're al aware of progress, I'll close this.
