### ISSUE TITLE
Review the calculation of disease risk

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#305]
James asked about the calculation of ORR (Overall Relative Risk) of diseases - is it sensible to divide the relative risks over the average relative risk for the whole population?

**Comment by jamesturner246** [comment]
Uploading the STOP paper appendix for info.

[STOP-model-paper-appendix.pdf](https://github.com/imperialCHEPI/healthgps/files/14209025/STOP-model-paper-appendix.pdf)

From discussions with @israel-vieira and @jzhu20, I'm a bit more convinced that this is correct. Let me know if you see something wrong.

Incidence is constant, taken from the beginning of the simulation, as is the expected risk from factors and disease taken at start.

Therefore, in order to 'update' incidence for a given year (as it were), you multiply it by average risks *at the time*, divided by the expected risks recorded at start:

```
P_disease = incidence * (mean_risk_at_current / mean_risk_at_start)
```

This gives `P_disease = incidence * (x / x)` for some `x` when mean current risk equals mean start risk, with incidence taken at start. This is what you want, since, if risk hasn't changed, probability of new disease should equal `incidence`.

**Comment by jzhu20** [comment]
I reckon that, for a given year (or we understand it as for a given distribution of risk factors and diseases), 

- adjusted incidence rate of a disease = incidence rate (by age and gender, assumed constant over time) * ORR
- ORR = multiplication of all the relative risks / population-level average of relative risks

where the population-level average of relative risks is changing over distribution of risk factors and diseases, but for each age*gender group at a time, it's constant.
Population-level average of ORR is constantly 1, i.e., E(ORR)=1, so that
E(adjusted incidence rate of a disease) = E(incidence rate) * E(ORR) = E(incidence rate), which makes sense; otherwise, population-level incidence will change over time.

**Comment by jamesturner246** [comment]
Continued in  #308
