### ISSUE TITLE
Test: Exaggeration of sodium RR

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#322]
Exaggerate RR of sodium to 10000 times, with RR of BMI removed.

**Comment by jzhu20** [comment]
![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/760afb13-eac0-4273-9ebd-77be7a919ce0)
![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/b8db13bf-ceaf-450d-bd6c-0d9db983fac6)

**Comment by jzhu20** [comment]
Comparing the two sets of plots above, the prevalence of the new diseases (ihd, stroke, etc.) doesn't seem to change at all as the relative risks of sodium change. Is it strange to you? @jamesturner246

**Comment by jamesturner246** [comment]
I think I see what's going on here.

Did you change the relative risk to sodium, or the intervention effect of sodium? If it's the relative risk, then I'm not too surprised  it doesn't change much, since the relative risk of everything is normalised to the mean of the initial risk (including your high relative risk to sodium values).

Try again with the relative risk values set back to their originals, but exaggerate the policy effect on sodium instead.

**Comment by jzhu20** [comment]
![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/fcb833fc-b69e-473b-b850-699e85489046)



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/824ca334-de7d-435a-8ae0-8668dca341ba)
