### ISSUE TITLE
[BUG] Auto-merging of bot PRs broken

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps#443]
I borrowed @AdrianDAlessandro's config for automerging PRs from dependabot and the pre-commit bot. Bizarrely, the workflow only also seems to be activated for other PRs though. See e.g. my PR here: https://github.com/imperialCHEPI/healthgps/actions/runs/9498223239/job/26176474545?pr=440

The config file is here and I think it should be identical to the one in the `pip-tools-template` repo: https://github.com/imperialCHEPI/healthgps/blob/main/.github/workflows/auto-merge.yml

Any ideas @AdrianDAlessandro?

I've disabled auto-merges for now while we figure this out.

**Comment by AdrianDAlessandro** [comment]
Seems like that specific workflow was run because the pre-commit bot made a commit to the branch, which satisfies the `github.actor == 'pre-commit-ci[bot]'` requirement, so it runs.

And it looks like it ran fine here - https://github.com/imperialCHEPI/healthgps/pull/435

But it's not merging because the branch protection rules require approval and the auto-merge doesn't also approve the PR. You can add this into the `run` step: `gh pr review --approve "$PR_URL"` (like in [gridlington](https://github.com/ImperialCollegeLondon/gridlington-datahub/blob/main/.github/workflows/auto-merge.yml)

**Comment by AdrianDAlessandro** [comment]
> Seems like that specific workflow was run because the pre-commit bot made a commit to the branch, which satisfies the `github.actor == 'pre-commit-ci[bot]'` requirement, so it runs.

Expanding on this. This means that if you want to use this workflow as is, you will have to change the pre-commit ci configuration to stop it automatically making changes in PRs, otherwise when it makes a change it will automatically merge the PR.

Either that, or you will need to find a more granular way of checking `github.actor` so that it's the actor that opened the pull request instead of the last actor to make a commit.

**Comment by alexdewar** [comment]
Thanks! That's really helpful.

It seems like there is a way to get the author of the PR rather than the last committer, so maybe we can just use that instead: https://github.com/orgs/community/discussions/25502

**Comment by alexdewar** [comment]
@dalonsoa I've noticed that you've tagged this as "in progress". Is someone else working on this? I haven't assigned myself to it yet (though I was planning on doing so)
